name: comment-on-merge.yml
on: pull_request
jobs:
  list_commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out game system
        uses: actions/checkout@v4
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install GitPython
        run: pip install GitPython
      - name: Run git diff
        run: git diff HEAD origin/main
